apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: openldaps.charts.helm.k8s.io
spec:
  group: charts.helm.k8s.io
  names:
    kind: OpenLDAP
    listKind: OpenLDAPList
    plural: openldaps
    singular: openldap
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
